config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: "oauth/applications",
      authorized_applications: "oauth/authorized_applications"
  end

  resources :comments
  resources :devices
  resources :teams
  resources :the_users do
    collection do
      get :show_complete_email_page
      post :complete_email
      get :is_email_existing
    end
  end

  root to: "topics#index"
  match "/uploads/:path(![large|lg|md|sm|xs])", to: "home#uploads", via: :get, constraints: {
    path: /[\w\d.\/\-]+/i
  }
  get "status", to: "home#status"

  devise_for :users, path: "account", controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resource :setting do
    member do
      get :account
      get :password
      get :profile
      get :reward
    end
  end

  # SSO
  namespace :auth do
    resource :sso, controller: "sso" do
      collection do
        get :login
        get :provider
      end
    end
  end

  delete "setting/auth/:provider", to: "settings#auth_unbind", as: "auth_unbind_setting"

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get "topics/node:id", to: "topics#node", as: "node_topics"
  get "topics/node:id/feed", to: "topics#node_feed", as: "feed_node_topics", defaults: {format: "xml"}

  resources :topics do
    member do
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      post :action
      # ban popup window
      get :ban
      post :read
    end

    collection do
      get :no_reply
      get :popular
      get :last
      get :last_reply
      get :banned
      get :excellent
      get :favorites
      get :feed, defaults: {format: "xml"}
      post :preview
    end

    resources :replies do
      member do
        get :reply_to
      end
    end
  end

  resources :photos
  resources :likes

  get "/search", to: "search#index", as: "search"
  get "/search/users", to: "search#users", as: "search_users"

  namespace :admin do
    root to: "dashboards#index", as: "root"
    resource :dashboards do
      collection do
        post :reboot
      end
    end
    resources :site_configs
    resources :replies do
      member do
        post :revert
      end
    end
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :revert
      end
    end
    resources :nodes
    resources :users, constraints: {id: /[#{User::LOGIN_FORMAT}]*/o} do
      member do
        delete :clean
      end
    end
    resources :photos
    resources :comments
    resources :locations
    resources :applications
    resources :stats
    resources :plugins
  end

  get "api", to: "home#api", as: "api"
  get "markdown", to: "home#markdown", as: "markdown"

  namespace :api do
    namespace :v3 do
      get "hello", to: "root#hello"

      resource :devices
      resource :likes
      resources :nodes
      resources :photos
      resources :notifications do
        collection do
          post :read
          get :unread_count
          delete :all
        end
      end
      resources :topics do
        member do
          post :update
          get :replies
          post :replies
          post :follow
          post :unfollow
          post :favorite
          post :unfavorite
          post :ban
          post :action
        end
      end
      resources :replies do
        member do
          post :update
        end
      end
      resources :users do
        collection do
          get :me
          get :is_email_available
        end
        member do
          get :topics
          get :replies
          get :favorites
          get :followers
          get :following
          get :blocked
          post :follow
          post :unfollow
          post :block
          post :unblock
        end
      end

      match "*path", to: "root#not_found", via: :all
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: "sidekiq"
    mount PgHero::Engine, at: "pghero"
    mount ExceptionTrack::Engine, at: "exception-track"
  end

  mount Notifications::Engine, at: "notifications"

  # WARRING！请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  get "users/city/:id", to: "users#city", as: "location_users"
  get "users", to: "users#index", as: "users"

  constraints(id: /[#{User::LOGIN_FORMAT}]*/o) do
    resources :users, path: "", as: "users" do
      member do
        get :feed
        # User only
        get :topics
        get :replies
        get :favorites
        get :blocked
        post :block
        post :unblock
        post :follow
        post :unfollow
        get :followers
        get :following
        get :reward
      end

      resources :team_users, path: "people" do
        member do
          post :accept
          post :reject
        end
      end
    end
  end

  match "*path", to: "home#error_404", via: :all
end

app/models/topic/actions.rb
# frozen_string_literal: true

class Topic
  module Actions
    extend ActiveSupport::Concern

    included do
      enum grade: {ban: -1, normal: 0, excellent: 1}

      # Follow enum method override methods must in `included` block.

      def ban!(reason: "")
        transaction do
          update!(grade: :ban)
          if reason
            Reply.create_system_event!(action: "ban", topic_id: id, body: reason)
          end
        end
      end

      def excellent!
        transaction do
          Reply.create_system_event!(action: "excellent", topic_id: id)
          update!(grade: :excellent)
        end
      end

      def unexcellent!
        transaction do
          Reply.create_system_event!(action: "unexcellent", topic_id: id)
          update!(grade: :normal)
        end
      end
    end

    # Destroy record, and then log who deleted.
    def destroy_by(user)
      return false if user.blank?
      update_attribute(:who_deleted, user.login)
      destroy
    end

    def destroy
      super
      delete_notification_mentions
    end
  end
end

app/controllers/admin/topics_controller.rb
# frozen_string_literal: true

module Admin
  class TopicsController < Admin::ApplicationController
    before_action :set_topic, only: %i[show edit update destroy revert suggest unsuggest]

    def index
      @topics = Topic.unscoped
      if params[:q].present?
        qstr = "%#{params[:q].downcase}%"
        @topics = @topics.where("title LIKE ?", qstr)
      end
      if params[:login].present?
        u = User.find_by_login(params[:login])
        @topics = @topics.where("user_id = ?", u.try(:id))
      end
      @topics = @topics.order(id: :desc)
      @topics = @topics.includes(:node, :user).page(params[:page])
    end

    def show
      redirect_to edit_admin_topic_path(@topic.id)
    end

    def new
      @topic = Topic.new
    end

    def edit
    end

    def create
      @topic = Topic.new(params[:topic].permit!)

      if @topic.save
        redirect_to(admin_topics_path, notice: "话题创建成功")
      else
        render action: "new"
      end
    end

    def update
      if @topic.update(params[:topic].permit!)
        redirect_to(admin_topics_path, notice: "话题更新成功")
      else
        render action: "edit"
      end
    end

    def destroy
      @topic.destroy_by(current_user)

      redirect_to(admin_topics_path)
    end

    def revert
      @topic.update_attribute(:deleted_at, nil)
      redirect_to(admin_topics_path)
    end

    def suggest
      @topic.update_attribute(:suggested_at, Time.now)
      redirect_to(@topic, notice: t("topics.topic_pin_successfully"))
    end

    def unsuggest
      @topic.update_attribute(:suggested_at, nil)
      redirect_to(@topic, notice: t("topics.topic_unpin_successfully"))
    end

    private

    def set_topic
      @topic = Topic.unscoped.find(params[:id])
    end
  end
end

app/controllers/api/v3/topics_controller.rb
# frozen_string_literal: true

module Api
  module V3
    class TopicsController < Api::V3::ApplicationController
      before_action :doorkeeper_authorize!, except: %i[index show replies]
      before_action :set_topic, except: %i[index create]

      # Get Topic List, like /topics page.
      #
      # GET /api/v3/topics
      #
      # @param type [String] order type, default: `last_actived`, %w(last_actived recent no_reply popular excellent)
      # @param node_id [Integer] Node ID, if present, will filter with node.
      # @param offset [Integer] default: 0
      # @param limit [Integer] default: 20, range: 1..150
      #
      # @return [Array<TopicSerializer>]
      def index
        optional! :type, default: "last_actived"
        optional! :node_id
        optional! :offset, default: 0
        optional! :limit, default: 20, values: 1..150

        params[:type] = params[:type].downcase

        if params[:node_id].blank?
          @topics = Topic
          if current_user
            @topics = @topics.without_nodes(current_user.block_node_ids)
            @topics = @topics.without_users(current_user.block_user_ids)
          else
            @topics = @topics.without_hide_nodes
          end
        else
          @node = Node.find(params[:node_id])
          @topics = @node.topics
        end

        current_user&.touch_last_online_ts

        @topics = @topics.without_ban.fields_for_list.includes(:node, :user).send(scope_method_by_type)
        if %w[no_reply popular].index(params[:type])
          @topics = @topics.last_actived
        elsif params[:type] == "excellent"
          @topics = @topics.recent
        end

        @topics = @topics.offset(params[:offset]).limit(params[:limit])
      end

      # Get Topic Detail (not including replies)
      #
      # GET /api/v3/topics/:id
      #
      # @param id [Integer] Topic ID
      # @return [TopicDetailSerializer] In addition, meta contains the status of the current user on this topic.
      #
      # ```json
      # { followed: 'Is followed this Topic', liked: 'Is liked this Topic', favorited: 'Is favorited this Topic' }
      # ```
      def show
        @meta = {followed: false, liked: false, favorited: false}

        if current_user
          current_user.touch_last_online_ts
          # Create Notifications
          current_user.read_topic(@topic)
          @meta[:followed] = current_user.follow_topic?(@topic)
          @meta[:liked] = current_user.like_topic?(@topic)
          @meta[:favorited] = current_user.favorite_topic?(@topic)
        end
      end

      # Create Topic
      #
      # POST /api/v3/topics
      #
      # @param title [String] Title, [required]
      # @param node_id [Integer] Node ID, [required]
      # @param body [Markdown] format body, [required]
      # @return [TopicDetailSerializer]
      def create
        requires! :title
        requires! :body
        requires! :node_id

        raise AccessDenied.new("The current user does not have permission to create Topic.") unless can?(:create, Topic)

        @topic = current_user.topics.new(title: params[:title], body: params[:body])
        @topic.node_id = params[:node_id]
        @topic.save!

        render "show"
      end

      # Update Topic
      #
      # POST /api/v3/topics/:id
      #
      # @param title [String] Title, [required]
      # @param node_id [Integer] Node ID, [required]
      # @param body [String] Markdown format body, [required]
      # @return [TopicDetailSerializer]
      def update
        requires! :title
        requires! :body
        requires! :node_id

        raise AccessDenied unless can?(:update, @topic)

        if @topic.lock_node == false || can?(:lock_node, @topic)
          # Only admin can change node, when it's has been locked
          @topic.node_id = params[:node_id]

          if @topic.node_id_changed? || can?(:lock_node, @topic)
            # Lock node when admin update
            @topic.lock_node = true
          end
        end
        @topic.title = params[:title]
        @topic.body = params[:body]
        @topic.save!

        render "show"
      end

      # 删除话题
      #
      # DELETE /api/v3/topics/:id
      def destroy
        raise AccessDenied unless can?(:destroy, @topic)
        @topic.destroy_by(current_user)
        render json: {ok: 1}
      end

      # 获取话题的回帖列表
      #
      # GET /api/v3/topics/:id/replies
      #
      # @param offset [Integer] default: 0
      # @param limit [Integer] default: 20, range: 1..150
      # @return [Array<ReplySerializer]>
      def replies
        if request.post?
          create_replies
          return
        end

        params[:limit] ||= 20

        @replies = Reply.unscoped.where(topic_id: @topic.id).order(:id).includes(:user)
        @replies = @replies.offset(params[:offset].to_i).limit(params[:limit].to_i)
        @user_liked_reply_ids = current_user&.like_reply_ids_by_replies(@replies) || []
        @meta = {user_liked_reply_ids: @user_liked_reply_ids}
      end

      # 创建对话题的回帖
      #
      # POST /api/v3/topics/:id/replies
      #
      # @param body [String] 回帖内容，[required]
      # @return [ReplySerializer] 创建的回帖信息
      def create_replies
        doorkeeper_authorize!

        requires! :body

        raise AccessDenied.new("The current user does not have permission to reply to topics.") unless can?(:create, Reply)

        @reply = @topic.replies.build(body: params[:body])
        @reply.user_id = current_user.id
        @reply.save!
        render "api/v3/replies/show"
      end

      # Follow Topic
      #
      # POST /api/v3/topics/:id/follow
      def follow
        current_user.follow_topic(@topic)
        render json: {ok: 1}
      end

      # Unfollow Topic
      #
      # POST /api/v3/topics/:id/unfollow
      def unfollow
        current_user.unfollow_topic(@topic)
        render json: {ok: 1}
      end

      # Favorite Topic
      #
      # POST /api/v3/topics/:id/favorite
      def favorite
        current_user.favorite_topic(@topic.id)
        render json: {ok: 1}
      end

      # Unfovorite Topic
      #
      # POST /api/v3/topics/:id/unfavorite
      def unfavorite
        current_user.unfavorite_topic(@topic.id)
        render json: {ok: 1}
      end

      # Ban Topic (Admin only)
      # [Deprecated] use POST /api/v3/topics/:id/action
      #
      # POST /api/v3/topics/:id/ban
      def ban
        raise AccessDenied.new("The current user does not have the authority to block other people's topics.") unless can?(:ban, @topic)
        @topic.ban!
        render json: {ok: 1}
      end

      # Actions
      # NOTE: The types have different permissions, see GET /api/v3/topics/:id retrurn abilities
      #
      # POST /api/v3/topics/:id/action?type=:type
      # @param type [String] action type, ban - Ban, normal - Unban, excellent - Excellent, unexcellent - Unexcellent, close - Close Topic, open - Reopen Topic
      def action
        raise AccessDenied unless can?(params[:type].to_sym, @topic)

        case params[:type]
        when "excellent"
          @topic.excellent!
        when "unexcellent"
          @topic.unexcellent!
        when "normal"
          @topic.normal!
        when "ban"
          @topic.ban!
        when "close"
          @topic.close!
        when "open"
          @topic.open!
        end
        render json: {ok: 1}
      end

      private

      def set_topic
        @topic = Topic.find(params[:id])
      end

      def scope_method_by_type
        case params[:type]
        when "last_actived" then :last_actived
        when "recent" then :recent
        when "no_reply" then :no_reply
        when "popular" then :popular
        when "excellent" then :excellent
        else
          :last_actived
        end
      end
    end
  end
end

app/helpers/topics_helper.rb
# frozen_string_literal: true

require "digest/md5"
module TopicsHelper
  def topic_favorite_tag(topic, opts = {})
    return "" if current_user.blank?
    opts[:class] ||= ""
    class_name = ""
    link_title = t("common.favorite")
    if current_user&.favorite_topic?(topic)
      class_name = "active"
      link_title = t("common.unfavorite")
    end

    if opts[:class].present?
      class_name += " " + opts[:class]
    end

    link_to(icon_tag("bookmark"), "#", :title => link_title, :class => "bookmark #{class_name}", "data-id" => topic.id)
  end

  def topic_follow_tag(topic, opts = {})
    return "" if current_user.blank?
    return "" if topic.blank?
    return "" if owner?(topic)
    opts[:class] ||= ""
    class_name = "follow"
    class_name += " active" if current_user.follow_topic?(topic)
    if opts[:class].present?
      class_name += " " + opts[:class]
    end
    link_to(icon_tag("bell"), "#", :title => t("common.subscribe"), "data-id" => topic.id, :class => class_name)
  end

  def topic_title_tag(topic, opts = {})
    return t("topics.topic_was_deleted") if topic.blank?
    if opts[:reply]
      index = topic.floor_of_reply(opts[:reply])
      path = main_app.topic_path(topic, anchor: "reply#{index}")
    else
      path = main_app.topic_path(topic)
    end
    link_to(topic.title, path, title: topic.title, class: "topic-title")
  end

  def topic_excellent_tag(topic)
    return "" unless topic.excellent?
    icon_tag("award")
  end

  def topic_close_tag(topic)
    return "" unless topic.closed?
    content_tag(:i, "", title: t("topics.closed_tooltip"), class: "fa fa-check-circle", "data-bs-toggle": "tooltip")
  end

  def render_node_name(node)
    return "" if node.blank?
    link_to(node.name, main_app.node_topics_path(node.id), class: "node")
  end
end

app/views/topics/_ban.html.erb
<div class="modal" id="ban-modal" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for('', url: action_topic_path(topic, type: "ban"), method: "POST", remote: true) do |f| %>
        <div class="modal-header">
          <div class="modal-title"><%= t("topics.ban_title") %></div>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <div class="mb-3">
            <select class="form-control" onchange="$('#ban-modal textarea').val($(this).val())" name="reason">
              <option value="" selected><%= t("topics.ban_directly") %></option>
              <% Setting.ban_reasons.each do |str| %>
                <option value="<%= str %>"><%= str %></option>
              <% end %>
            </select>
          </div>
          <div>
            <label><%= t("topics.ban_with_reason") %></label>
            <textarea class="form-control" name="reason_text" rows="4"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary"><%= t("common.ok") %></button>
          <a class="btn btn-secondary" data-bs-dismiss ="modal"><%= t("common.cancel") %></a>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/_buttons.html.erb
<div class="opts">
  <% if !turbolinks_ios? %>
    <%= likeable_tag(@topic) %>
    <%= topic_follow_tag(@topic) %>
    <%= topic_favorite_tag(@topic) %>
  <% end %>
  <div class="float-right">
    <div class="dropdown">
      <a href="#" data-bs-toggle ="dropdown">
        <%= icon_tag("ellipsis-v") %>
      </a>
      <%= render "menu" %>
    </div>
  </div>
</div>

app/views/topics/_form.html.erb
<%= form_for @topic, remote: true, class: "form", html: { tb: 'edit-topic' } do |f| %>
  <%= render "shared/error_messages", target: @topic %>
  <%= f.hidden_field :node_id %>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-prepend mr-1">
        <%= f.select :node_id, Node.sorted.name_options, {}, class: "bootstrap-select", data: { "live-search": true } %>
      </div>
      <%= f.text_field :title, class: "form-control", placeholder: t("topics.form.title_placeholder") %>
    </div>
  </div>
  <%= render "/shared/editor_toolbar" %>
  <div class="form-group">
    <%= f.text_area :body, class: "topic-editor form-control", rows: 20 %>
  </div>
  <% if Setting.has_module?(:team) %>
    <% if current_user.team_options.any? %>
      <div class='form-group'>
        <%= f.select :team_id, current_user.team_options, { include_blank: t("topics.form.no_team") }, { class: "bootstrap-select", data: { "live-search": true } } %>
      </div>
    <% end %>
  <% end %>
  <div class="form-actions md:justify-between hide-ios">
    <%= f.submit t("common.publish"), class: "btn btn-primary", 'data-disable-with' => t("common.saving"), 'data-tb' => "save-topic" %>
    <div class="hide-ios"><a href="/markdown" target="_blank"><i class="fa fa-life-ring"></i> <%= t("topics.form.markdown_guides") %></a></div>
  </div>
<% end %>

app/views/topics/_menu.html.erb
<div class="dropdown-menu dropdown-menu-end">
  <% if can?(:edit, @topic) %>
    <%= link_to t("topics.menu.edit"), edit_topic_path(@topic), class: "dropdown-item", data: { prefetch: false }  %>
  <% end %>
  <% if can?(:close, @topic) %>
    <% if !@topic.closed? %>
      <%= link_to t("topics.menu.close"), action_topic_path(@topic, type: 'close'), class: "dropdown-item", method: 'post', remote: true, "data-bs-toggle": 'tooltip' %>
    <% else %>
      <%= link_to t("topics.menu.reopen"), action_topic_path(@topic, type: 'open'), class: "dropdown-item", method: 'post', remote: true, "data-bs-toggle": 'tooltip' %>
    <% end %>
  <% end %>
  <% if can? :suggest, @topic %>
    <div class="dropdown-divider"></div>
    <% if !@topic.suggested_at.blank? %>
      <%= link_to t("topics.menu.unpin"), unsuggest_admin_topic_path(@topic), class: "dropdown-item", method: :post, remote: true %>
    <% else %>
      <%= link_to t("topics.menu.pin"), suggest_admin_topic_path(@topic), class: "dropdown-item", method: :post, remote: true %>
    <% end %>
    <% if !@topic.excellent? %>
      <%= link_to t("topics.menu.excellent"), action_topic_path(@topic.id, type: 'excellent'), class: "dropdown-item", method: :post, remote: true %>
    <% end %>
    <% if !@topic.ban? %>
      <%= link_to t("topics.menu.ban"), ban_topic_path(@topic), class: "dropdown-item", remote: true %>
    <% else %>
      <%= link_to t("topics.menu.unban"), action_topic_path(@topic, type: 'normal'), class: "dropdown-item", method: :post, remote: true %>
    <% end %>
  <% end %>
  <% if can?(:destroy, @topic) %>
    <div class="dropdown-divider"></div>
    <%= link_to t("topics.menu.delete"), topic_path(@topic.id), class: "dropdown-item", method: :delete, remote: true, 'data-confirm': t("common.confirm_delete"), title: "删除本帖" %>
  <% end %>
</div>

app/views/topics/_reply_form.html.erb
<%= render "/shared/editor_toolbar" %>
<%= form_for(Reply.new, url: topic_replies_path(@topic), remote: true, id: "new_reply") do |f| %>

  <div class="form-group">
    <%= f.text_area :body, class: "topic-editor form-control", rows: "4", tabindex: "1" %>
  </div>
  <%= f.hidden_field :reply_to_id %>
  <div class="submit-buttons">
    <button type="submit" id="reply-button" class="btn btn-primary" tabindex="2", data-disable-with='<%= t("topics.submit_reply") %>'><%= t("topics.submit_reply")%></button>
    <span class="help-inline" style="padding-left: 5px;" title="Ctrl + Enter"><kbd>Command</kbd> + <kbd>Enter</kbd></span>

    <div class="float-right"><a href="/markdown" target="_blank"><%= t("topics.form.markdown_guides") %></a></div>
  </div>
<% end %>

app/views/topics/_sidebar_box_node_recent_topics.html.erb
<% cache(["sidebar_for_node_recent_topics", topic.node_id, Time.now.strftime("%Y-%m-%d %H")]) do %>
  <%
  limit = [[topic.replies_count, 1].max, 10].min
  topics = Topic.where(:id.ne => topic.id, :node_id => topic.node_id).recent.limit(limit)
  %>

  <% if topics.present? %>
  <div class="card">
    <div class="card-header"><%= t("topics.node_recent_topics") %></div>
    <ul class="list-group list-group-flush">
    <% topics.each do |item| %>
      <li class="list-group-item"><%= link_to(truncate(item.title, length: 30), topic_path(item), title: item.title) %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<% end %>

app/views/topics/_topic.html.erb
<%= render TopicComponent.new(topic: topic, type: (suggest ? "suggest" : "normal")) %>

app/views/topics/ban.js.erb
App.modal("<%= j(render('ban', topic: @topic)) %>");

app/views/topics/show.html.erb
<% title_tag @topic.title, description: @topic.description %>
<% content_for :scripts do %>
  <script type="text/javascript">
    Topics.topic_id = <%= @topic.id %>;
    <% if !@user_like_reply_ids.blank? %>
    Topics.user_liked_reply_ids = [<%= @user_like_reply_ids.join(",") %>];
    <% end %>
    $(document).ready(function(){
      <% if can?(:manage, Reply) %>
        $("#replies .reply a.edit").css('display','inline-block');
      <% elsif current_user %>
        $("#replies .reply a.edit[data-uid='<%= current_user.id %>']").css('display','inline-block');
      <% end %>

      <% if @topic.closed? %>
        $("#replies .reply .hideable").remove();
      <% end %>
      $.post("<%= read_topic_path(@topic) %>");
    })
  </script>
<% end %>
<div class="flex gap-4">
  <div class="grow w-3/4">
    <div class="topic-detail card mb-4">
      <%= render partial: "topics/topic_info", locals: { topic: @topic, node: @node } %>
      <% if @topic.excellent? %>
        <div class="label-awesome">
          <i class="fa fa-award awesome"></i> <%= t("topics.excellent_info_html") %>
          <% if can?(:close, @topic) %>
            <div class="float-right">
              <%= link_to icon_tag("close"), action_topic_path(@topic.id, type: 'normal'), method: :post, remote: true %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="card-body markdown markdown-toc">
        <%= raw Setting.before_topic_html %>
        <%= @topic.body_html %>
        <%= raw Setting.after_topic_html %>
      </div>
      <div class="card-footer clearfix">
        <%= render "buttons" %>
      </div>
    </div>
    <%= render partial: "ban_reason" %>
    <% if @replies.blank? %>
      <div class="no-result">
        <%= t("topics.no_replies") %>
      </div>
    <% else %>
      <div id="replies" class="card mb-4" data-last-floor="<%= @replies.count(:all) %>">
        <div class="items card-body">
          <%= render ReplyComponent.with_collection(@replies, topic: @topic, show_raw: @show_raw) %>
        </div>
      </div>
    <% end %>
    <% if current_user %>
      <% if @topic.closed? %>
        <div class="alert alert-info"><%= t("topics.closed_info_html", closed_at: l(@topic.closed_at, format: :long)) %></div>
      <% else %>
        <div id="reply" class="card mb-4">
          <div class="card-body">
            <div class="card-title hide-ios"><%= t("topics.reply") %></div>
            <% if can? :create, Reply %>
              <%= render 'reply_form' %>
            <% else %>
              <div class="alert alert-info">
                <%= t("topics.newbi_info_html") %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="card mb-4">
        <div class="card-body">
          <div id="reply" class="form box">
            <div style="padding:20px;" data-turbolinks-action="replace">
              <%= t("topics.need_login_to_reply_html") %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if !mobile? %>
    <div class="hidden md:flex md:w-60 lg:w-72 shrink-0">
      <%= render 'topic_sidebar' %>
    </div>
  <% else %>
    <div class="move-page-buttons">
      <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="top"><i class="fa fa-arrow-up"></i></a>
      <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="bottom"><i class="fa fa-arrow-down"></i></a>
    </div>
  <% end %>
</div>